<?php

/**
 * -----------------------------------------------------
 * BASE64 URL SAFE ENCODE
 * -----------------------------------------------------
 * Converts binary/string data into URL-safe Base64.
 *
 * BillDesk uses:
 *   +  => -
 *   /  => _
 * and removes trailing =
 */
function b64e($data)
{
    return rtrim(
        strtr(
            base64_encode($data), // Convert to Base64
            '+/',                 // Replace
            '-_'                  // With URL-safe chars
        ),
        '='                       // Remove trailing =
    );
}

/**
 * -----------------------------------------------------
 * BASE64 URL SAFE DECODE
 * -----------------------------------------------------
 * Converts URL-safe Base64 back to original data.
 */
function b64d($data)
{
    return base64_decode(
        strtr(
            $data,
            '-_', // URL-safe chars
            '+/'  // Original Base64 chars
        )
        .
        str_repeat(
            '=',
            (4 - strlen($data) % 4) % 4
        )
    );
}

/**
 * -----------------------------------------------------
 * ENCRYPT REQUEST PAYLOAD
 * -----------------------------------------------------
 * Converts normal JSON payload into JWE.
 *
 * Input:
 * {
 *   "orderid":"123",
 *   "amount":"100"
 * }
 *
 * Output:
 * HEADER..IV.CIPHERTEXT.TAG
 */
function bd_encrypt(
    array $payload,
    string $enc_key,
    string $enc_key_id,
    string $client_id
): string {

    // BillDesk requires 32-byte AES key
    if (strlen($enc_key) !== 32) {
        throw new Exception(
            'Encryption key must be exactly 32 characters.'
        );
    }

    /**
     * Create JWE Header
     *
     * alg = direct encryption
     * enc = AES256 GCM
     * kid = encryption key id
     * clientid = billdesk client id
     */
    $header = b64e(
        json_encode([
            'alg'      => 'dir',
            'enc'      => 'A256GCM',
            'kid'      => $enc_key_id,
            'clientid' => $client_id
        ])
    );

    // Generate random 12-byte IV
    $iv = random_bytes(12);

    // Authentication tag will be generated by OpenSSL
    $tag = '';

    /**
     * Encrypt Payload
     */
    $ciphertext = openssl_encrypt(
        json_encode($payload), // Data to encrypt
        'aes-256-gcm',         // Encryption algorithm
        $enc_key,              // Encryption key
        OPENSSL_RAW_DATA,
        $iv,                   // Initialization Vector
        $tag,                  // Authentication Tag
        $header,               // Additional Authenticated Data
        16                     // Tag length
    );

    // If encryption fails
    if ($ciphertext === false) {
        throw new Exception(
            'Encryption failed.'
        );
    }

    /**
     * Build JWE
     *
     * Format:
     * HEADER..IV.CIPHERTEXT.TAG
     */
    return implode('.', [
        $header,
        '',
        b64e($iv),
        b64e($ciphertext),
        b64e($tag)
    ]);
}

/**
 * -----------------------------------------------------
 * SIGN JWE
 * -----------------------------------------------------
 * Converts encrypted JWE into signed JWS.
 *
 * Input:
 * HEADER..IV.CIPHERTEXT.TAG
 *
 * Output:
 * HEADER.PAYLOAD.SIGNATURE
 */
function bd_sign(
    string $jwe,
    string $sign_key,
    string $sign_key_id,
    string $client_id
): string {

    // Ensure signing key exists
    if (empty($sign_key)) {
        throw new Exception(
            'Signing key is empty.'
        );
    }

    /**
     * JWS Header
     */
    $header = b64e(
        json_encode([
            'alg'      => 'HS256',
            'kid'      => $sign_key_id,
            'clientid' => $client_id
        ])
    );

    // Base64 encode encrypted payload
    $payload = b64e($jwe);

    /**
     * Generate HMAC SHA256 Signature
     */
    $signature = b64e(
        hash_hmac(
            'sha256',
            "$header.$payload",
            $sign_key,
            true
        )
    );

    /**
     * Final JWS
     *
     * HEADER.PAYLOAD.SIGNATURE
     */
    return "$header.$payload.$signature";
}

/**
 * -----------------------------------------------------
 * VERIFY SIGNATURE
 * -----------------------------------------------------
 * Used when BillDesk sends a response.
 *
 * Input:
 * HEADER.PAYLOAD.SIGNATURE
 *
 * Output:
 * Returns PAYLOAD if signature is valid
 */
function bd_verify(
    string $jws,
    string $sign_key
): string {

    // Ensure data exists
    if (empty($jws)) {
        throw new Exception(
            'Empty JWS received.'
        );
    }

    /**
     * Split into:
     * HEADER
     * PAYLOAD
     * SIGNATURE
     */
    $parts = explode('.', $jws);

    // JWS must contain exactly 3 parts
    if (count($parts) !== 3) {
        throw new Exception(
            'Invalid JWS format.'
        );
    }

    [$h, $p, $s] = $parts;

    /**
     * Generate expected signature
     */
    $expectedSignature = b64e(
        hash_hmac(
            'sha256',
            "$h.$p",
            $sign_key,
            true
        )
    );

    /**
     * Compare signatures safely
     */
    if (!hash_equals(
        $expectedSignature,
        $s
    )) {
        throw new Exception(
            'Signature verification failed.'
        );
    }

    /**
     * Return decoded payload
     *
     * This payload is still encrypted (JWE)
     */
    $payload = b64d($p);

    if ($payload === false) {
        throw new Exception(
            'Unable to decode payload.'
        );
    }

    return $payload;
}

/**
 * -----------------------------------------------------
 * DECRYPT JWE
 * -----------------------------------------------------
 * Used after signature verification.
 *
 * Input:
 * HEADER..IV.CIPHERTEXT.TAG
 *
 * Output:
 * PHP Array
 */
function bd_decrypt(
    string $jwe,
    string $enc_key
): array {

    // Ensure data exists
    if (empty($jwe)) {
        throw new Exception(
            'Empty JWE received.'
        );
    }

    // Validate key length
    if (strlen($enc_key) !== 32) {
        throw new Exception(
            'Encryption key must be exactly 32 characters.'
        );
    }

    /**
     * Split JWE
     *
     * HEADER
     * EMPTY
     * IV
     * CIPHERTEXT
     * TAG
     */
    $parts = explode('.', $jwe);

    // JWE must contain exactly 5 parts
    if (count($parts) !== 5) {
        throw new Exception(
            'Invalid JWE format.'
        );
    }

    [$hb64, , $iv64, $ct64, $tag64] = $parts;

    // Decode values
    $iv  = b64d($iv64);
    $ct  = b64d($ct64);
    $tag = b64d($tag64);

    if ($iv === false) {
        throw new Exception('Invalid IV.');
    }

    if ($ct === false) {
        throw new Exception('Invalid Cipher Text.');
    }

    if ($tag === false) {
        throw new Exception('Invalid Tag.');
    }

    /**
     * Decrypt using AES256-GCM
     */
    $plain = openssl_decrypt(
        $ct,
        'aes-256-gcm',
        $enc_key,
        OPENSSL_RAW_DATA,
        $iv,
        $tag,
        $hb64
    );

    if ($plain === false) {
        throw new Exception(
            'Decryption failed.'
        );
    }

    /**
     * Convert JSON string to PHP Array
     */
    $data = json_decode(
        $plain,
        true
    );

    if (
        json_last_error() !== JSON_ERROR_NONE
    ) {
        throw new Exception(
            'Invalid JSON after decryption: '
            . json_last_error_msg()
        );
    }

    return $data;
}